author: Bryan Lim
date: 2024/01/12
description: 'Detects when an access level is changed for a Google workspace application.

  An access level is part of BeyondCorp Enterprise which is Google Workspace''s way
  of enforcing Zero Trust model.

  An adversary would be able to remove access levels to gain easier access to Google
  workspace resources.

  '
detection:
  condition: selection
  selection:
    eventName: CHANGE_APPLICATION_SETTING
    eventService: admin.googleapis.com
    setting_name|startswith: ContextAwareAccess
falsepositives:
- Legitimate administrative activities changing the access levels for an application
id: 22f2fb54-5312-435d-852f-7c74f81684ca
level: medium
logsource:
  product: gcp
  service: google_workspace.admin
references:
- https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-application-settings
- https://support.google.com/a/answer/9261439
status: experimental
tags:
- attack.persistence
- attack.privilege_escalation
- attack.t1098.003
title: Google Workspace Application Access Level Modified
