author: Jonathan Cheong, oscd.community
date: 2020/10/15
description: Detects Obfuscated use of stdin to execute PowerShell
detection:
  condition: all of selection*
  selection:
    EventID: 4697
    ServiceFileName|contains|all:
    - cmd
    - powershell
  selection2:
    ServiceFileName|contains:
    - ${input}
    - noexit
  selection3:
    ServiceFileName|contains:
    - ' /c '
    - ' /r '
falsepositives:
- Unknown
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
level: high
logsource:
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
  product: windows
  service: security
modified: 2022/11/29
references:
- https://github.com/SigmaHQ/sigma/issues/1009
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
status: test
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation STDIN+ Launcher - Security
