author: Timur Zinniatullin, oscd.community
date: 2020/10/13
description: Detects Obfuscated Powershell via VAR++ LAUNCHER
detection:
  condition: selection
  selection:
    EventID: 4697
    ServiceFileName|contains:
    - '{0}'
    - '{1}'
    - '{2}'
    - '{3}'
    - '{4}'
    - '{5}'
    ServiceFileName|contains|all:
    - '&&set'
    - cmd
    - /c
    - -f
falsepositives:
- Unknown
id: 4c54ba8f-73d2-4d40-8890-d9cf1dca3d30
level: high
logsource:
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
  product: windows
  service: security
modified: 2022/11/29
references:
- https://github.com/SigmaHQ/sigma/issues/1009
related:
- id: 14bcba49-a428-42d9-b943-e2ce0f0f7ae6
  type: derived
status: test
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security
