alert:
- debug
description: Detects the execution of DeviceCredentialDeployment to hide a process
  from view
filter:
- query:
    query_string:
      query: process_path.keyword:*\\DeviceCredentialDeployment.exe
index: wazuh-alerts*
name: proc_creation_win_lolbin_device_credential_deployment
priority: 3
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
