alert:
- debug
description: Detects actions caused by the RedMimicry Winnti playbook a automated
  breach emulations utility
filter:
- query:
    query_string:
      query: (process_path.keyword:(*\\rundll32.exe OR *\\cmd.exe) AND process_command_line.keyword:(*gthread\-3.6.dll*
        OR *\\Windows\\Temp\\tmp.bat* OR *sigcmm\-2.4.dll*))
index: wazuh-alerts*
name: proc_creation_win_hktl_redmimicry_winnti_playbook
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
