alert:
- debug
description: Detects when a user enable developer features such as "Developer Mode"
  or "Application Sideloading". Which allows the user to install untrusted packages.
filter:
- query:
    query_string:
      query: ((process_path.keyword:*\\SystemSettingsAdminFlows.exe OR file_name_original:"SystemSettingsAdminFlows.EXE")
        AND process_command_line.keyword:*TurnOnDeveloperFeatures* AND process_command_line.keyword:(*DeveloperUnlock*
        OR *EnableSideloading*))
index: wazuh-alerts*
name: proc_creation_win_systemsettingsadminflows_turn_on_dev_features
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
