author: Peter Matkovski, IAI
date: 2023/03/06
description: Detect unix shell configuration modification. Adversaries may establish
  persistence through executing malicious commands triggered when a new shell is opened.
detection:
  condition: selection
  selection:
    name:
    - /etc/shells
    - /etc/profile
    - /etc/profile.d/*
    - /etc/bash.bashrc
    - /etc/bashrc
    - /etc/zsh/zprofile
    - /etc/zsh/zshrc
    - /etc/zsh/zlogin
    - /etc/zsh/zlogout
    - /etc/csh.cshrc
    - /etc/csh.login
    - /root/.bashrc
    - /root/.bash_profile
    - /root/.profile
    - /root/.zshrc
    - /root/.zprofile
    - /home/*/.bashrc
    - /home/*/.zshrc
    - /home/*/.bash_profile
    - /home/*/.zprofile
    - /home/*/.profile
    - /home/*/.bash_login
    - /home/*/.bash_logout
    - /home/*/.zlogin
    - /home/*/.zlogout
    type: PATH
falsepositives:
- Admin or User activity are expected to generate some false positives
id: a94cdd87-6c54-4678-a6cc-2814ffe5a13d
level: medium
logsource:
  product: linux
  service: auditd
modified: 2023/03/15
references:
- https://objective-see.org/blog/blog_0x68.html
- https://www.glitch-cat.com/p/green-lambert-and-attack
- https://www.anomali.com/blog/pulling-linux-rabbit-rabbot-malware-out-of-a-hat
related:
- id: e74e15cc-c4b6-4c80-b7eb-dfe49feb7fe9
  type: obsoletes
status: test
tags:
- attack.persistence
- attack.t1546.004
title: Unix Shell Configuration Modification
