author: Dimitrios Slamaris
date: 2017/05/15
description: This rule detects a DHCP server in which a specified Callout DLL (in
  registry) was loaded
detection:
  condition: selection
  selection:
    EventID: 1033
    Provider_Name: Microsoft-Windows-DHCP-Server
falsepositives:
- Unknown
id: 13fc89a9-971e-4ca6-b9dc-aa53a445bf40
level: high
logsource:
  product: windows
  service: system
modified: 2022/12/25
references:
- https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
- https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
- https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx
status: test
tags:
- attack.defense_evasion
- attack.t1574.002
title: DHCP Server Loaded the CallOut DLL
