alert:
- debug
description: Identifies when a Kubernetes account access a sensitive objects such
  as configmaps or secrets.
filter:
- query:
    query_string:
      query: operationName:("MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/CONFIGMAPS\/WRITE"
        OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/CONFIGMAPS\/DELETE" OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/SECRETS\/WRITE"
        OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/SECRETS\/DELETE")
index: wazuh-alerts*
name: azure_kubernetes_secret_or_config_object_access
priority: 3
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
