alert:
- debug
description: Detects all variations of obfuscated powershell IEX invocation code generated
  by Invoke-Obfuscation framework from the code block linked in the references
filter:
- query:
    query_string:
      query: (event_id:"4697" AND (service_image_path.keyword:/\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[/
        OR service_image_path.keyword:/\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[/
        OR service_image_path.keyword:/\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[/
        OR service_image_path.keyword:/\$env:ComSpec\[(\s*\d{1,3}\s*,){2}/ OR service_image_path.keyword:/\\*mdr\*\W\s*\)\.Name/
        OR service_image_path.keyword:/\$VerbosePreference\.ToString\(/ OR service_image_path.keyword:/\String\]\s*\$VerbosePreference/))
index: wazuh-alerts*
name: win_security_invoke_obfuscation_obfuscated_iex_services_security
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
