alert:
- debug
description: Detects certificate creation with template allowing risk permission subject
filter:
- query:
    query_string:
      query: ((event_id:"4898" AND TemplateContent.keyword:*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*)
        OR (event_id:"4899" AND NewTemplateContent.keyword:*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*))
index: wazuh-alerts*
name: win_security_adcs_certificate_template_configuration_vulnerability
priority: 4
realert:
  minutes: 0
type: any

is_enabled: false
