alert:
- debug
description: Detects certificate creation with template allowing risk permission subject
  and risky EKU
filter:
- query:
    query_string:
      query: ((event_id:"4898" AND TemplateContent.keyword:(*1.3.6.1.5.5.7.3.2* OR
        *1.3.6.1.5.2.3.4* OR *1.3.6.1.4.1.311.20.2.2* OR *2.5.29.37.0*) AND TemplateContent.keyword:*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*)
        OR (event_id:"4899" AND NewTemplateContent.keyword:(*1.3.6.1.5.5.7.3.2* OR
        *1.3.6.1.5.2.3.4* OR *1.3.6.1.4.1.311.20.2.2* OR *2.5.29.37.0*) AND NewTemplateContent.keyword:*CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT*))
index: wazuh-alerts*
name: win_security_adcs_certificate_template_configuration_vulnerability_eku
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
