author: Thomas Patzke
date: 2017/08/06
description: Detects suspicious Spring framework exceptions that could indicate exploitation
  attempts
detection:
  condition: keywords
  keywords:
  - AccessDeniedException
  - CsrfException
  - InvalidCsrfTokenException
  - MissingCsrfTokenException
  - CookieTheftException
  - InvalidCookieException
  - RequestRejectedException
falsepositives:
- Application bugs
id: ae48ab93-45f7-4051-9dfe-5d30a3f78e33
level: medium
logsource:
  category: application
  product: spring
modified: 2020/09/01
references:
- https://docs.spring.io/spring-security/site/docs/current/api/overview-tree.html
status: stable
tags:
- attack.initial_access
- attack.t1190
title: Spring Framework Exceptions
