author: Muhammad Faisal (@faisalusuf)
date: 2024/02/25
description: Detects changes to the bitbucket audit log configuration.
detection:
  condition: selection
  selection:
    auditType.action: Audit log configuration updated
    auditType.category: Auditing
falsepositives:
- Legitimate user activity.
id: 6aa12161-235a-4dfb-9c74-fe08df8d8da1
level: medium
logsource:
  definition: 'Requirements: "Basic" log level is required to receive these audit
    events.'
  product: bitbucket
  service: audit
references:
- https://confluence.atlassian.com/bitbucketserver/view-and-configure-the-audit-log-776640417.html
status: experimental
tags:
- attack.defense_evasion
- attack.t1562.001
title: Bitbucket Audit Log Configuration Updated
