author: Muhammad Faisal (@faisalusuf)
date: 2024/02/25
description: Detects Bitbucket global SSH access configuration changes.
detection:
  condition: selection
  selection:
    auditType.action: SSH settings changed
    auditType.category: Global administration
falsepositives:
- Legitimate user activity.
id: 16ab6143-510a-44e2-a615-bdb80b8317fc
level: medium
logsource:
  definition: 'Requirements: "Advance" log level is required to receive these audit
    events.'
  product: bitbucket
  service: audit
references:
- https://confluence.atlassian.com/bitbucketserver/audit-log-events-776640423.html
- https://confluence.atlassian.com/bitbucketserver/enable-ssh-access-to-git-repositories-776640358.html
status: experimental
tags:
- attack.lateral_movement
- attack.defense_evasion
- attack.t1562.001
- attack.t1021.004
title: Bitbucket Global SSH Settings Changed
