author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/08/05
description: 'Detects when someone is adding or removing applications or folders from
  exploit guard "ProtectedFolders" or "AllowedApplications"

  '
detection:
  allowed_apps_key:
    EventID: 5007
    NewValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\AllowedApplications\
  allowed_apps_path:
    NewValue|contains:
    - \Users\Public\
    - \AppData\Local\Temp\
    - \Desktop\
    - \PerfLogs\
    - \Windows\Temp\
  condition: all of allowed_apps* or protected_folders
  protected_folders:
    EventID: 5007
    OldValue|contains: \Windows Defender\Windows Defender Exploit Guard\Controlled
      Folder Access\ProtectedFolders\
falsepositives:
- Unlikely
id: a3ab73f1-bd46-4319-8f06-4b20d0617886
level: high
logsource:
  product: windows
  service: windefend
modified: 2022/12/06
references:
- https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
status: test
tags:
- attack.defense_evasion
- attack.t1562.001
title: Windows Defender Exploit Guard Tamper
