author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/12/06
description: Detects disabling of the "Automatic Sample Submission" feature of Windows
  Defender.
detection:
  condition: selection
  selection:
    EventID: 5007
    NewValue|contains: \Real-Time Protection\SubmitSamplesConsent = 0x0
falsepositives:
- Administrator activity (must be investigated)
id: 91903aba-1088-42ee-b680-d6d94fe002b0
level: low
logsource:
  product: windows
  service: windefend
references:
- https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide
- https://bidouillesecurity.com/disable-windows-defender-in-powershell/#DisableAntiSpyware
related:
- id: 1321dc4e-a1fe-481d-a016-52c45f0c8b4f
  type: similar
- id: a3ab73f1-bd46-4319-8f06-4b20d0617886
  type: similar
- id: 801bd44f-ceed-4eb6-887c-11544633c0aa
  type: similar
status: stable
tags:
- attack.defense_evasion
- attack.t1562.001
title: Windows Defender Submit Sample Feature Disabled
