alert:
- debug
description: Detect unix shell configuration modification. Adversaries may establish
  persistence through executing malicious commands triggered when a new shell is opened.
filter:
- query:
    query_string:
      query: (type:"PATH" AND name.keyword:(\/etc\/shells OR \/etc\/profile OR \/etc\/profile.d\/*
        OR \/etc\/bash.bashrc OR \/etc\/bashrc OR \/etc\/zsh\/zprofile OR \/etc\/zsh\/zshrc
        OR \/etc\/zsh\/zlogin OR \/etc\/zsh\/zlogout OR \/etc\/csh.cshrc OR \/etc\/csh.login
        OR \/root\/.bashrc OR \/root\/.bash_profile OR \/root\/.profile OR \/root\/.zshrc
        OR \/root\/.zprofile OR \/home\/*\/.bashrc OR \/home\/*\/.zshrc OR \/home\/*\/.bash_profile
        OR \/home\/*\/.zprofile OR \/home\/*\/.profile OR \/home\/*\/.bash_login OR
        \/home\/*\/.bash_logout OR \/home\/*\/.zlogin OR \/home\/*\/.zlogout))
index: wazuh-alerts*
name: lnx_auditd_unix_shell_configuration_modification
priority: 3
realert:
  minutes: 0
type: any

is_enabled: false
