alert:
- debug
description: Detects an appx package added the pipeline of the "to be processed" packages
  which is downloaded from a suspicious domain
filter:
- query:
    query_string:
      query: (event_id:"854" AND process_path.keyword:(*.githubusercontent.com* OR
        *anonfiles.com* OR *cdn.discordapp.com* OR *cdn.discordapp.com\/attachments\/*
        OR *ddns.net* OR *dl.dropboxusercontent.com* OR *ghostbin.co* OR *glitch.me*
        OR *gofile.io* OR *hastebin.com* OR *mediafire.com* OR *mega.nz* OR *onrender.com*
        OR *paste.ee* OR *pastebin.com* OR *pastebin.pl* OR *pastetext.net* OR *privatlab.com*
        OR *privatlab.net* OR *send.exploit.in* OR *sendspace.com* OR *storage.googleapis.com*
        OR *storjshare.io* OR *supabase.co* OR *temp.sh* OR *transfer.sh* OR *ufile.io*))
index: wazuh-alerts*
name: win_appxdeployment_server_susp_domains
priority: 2
realert:
  minutes: 0
type: any

is_enabled: true
timestamp_type: iso
timestamp_field: '@timestamp'
