alert:
- debug
description: Detects an appx package installation with the error code "0x80073cff"
  which indicates that the package didn't meet the signing requirements and could
  be suspicious
filter:
- query:
    query_string:
      query: (event_id:"401" AND ErrorCode:"0x80073cff")
index: wazuh-alerts*
name: win_appxdeployment_server_susp_appx_package_installation
priority: 3
realert:
  minutes: 0
type: any

is_enabled: false
