alert:
- debug
description: Detects an appx package added the pipeline of the "to be processed" packages
  which is located in uncommon locations
filter:
- query:
    query_string:
      query: (event_id:"854" AND (NOT ((process_path.keyword:(*C\:\\Program\ Files\\WindowsApps\\*
        OR *C\:\\Program\ Files\ \(x86\)\\* OR *C\:\\Windows\\SystemApps\\* OR *C\:\\Windows\\PrintDialog\\*
        OR *C\:\\Windows\\ImmersiveControlPanel\\* OR *x\-windowsupdate\:\/\/* OR
        *file\:\/\/\/C\:\/Program%20Files*)) OR (process_path.keyword:(*https\:\/\/statics.teams.cdn.office.net\/*
        OR *microsoft.com*)))))
index: wazuh-alerts*
name: win_appxdeployment_server_uncommon_package_locations
priority: 3
realert:
  minutes: 0
type: any

is_enabled: true
timestamp_type: iso
timestamp_field: '@timestamp'
