alert:
- debug
description: Detects the Setting of Windows Defender Exclusions
filter:
- query:
    query_string:
      query: (event_id:"5007" AND NewValue.keyword:*\\Microsoft\\Windows\ Defender\\Exclusions*)
index: wazuh-alerts*
name: win_defender_config_change_exclusion_added
priority: 3
realert:
  minutes: 0
type: any

is_enabled: true
timestamp_type: iso
timestamp_field: '@timestamp'
