alert:
- debug
description: "Detects when someone is adding or removing applications or folders from
  exploit guard \"ProtectedFolders\" or \"AllowedApplications\"\n"
filter:
- query:
    query_string:
      query: ((event_id:"5007" AND NewValue.keyword:*\\Windows\ Defender\\Windows\
        Defender\ Exploit\ Guard\\Controlled\ Folder\ Access\\AllowedApplications\\*
        AND NewValue.keyword:(*\\Users\\Public\\* OR *\\AppData\\Local\\Temp\\* OR
        *\\Desktop\\* OR *\\PerfLogs\\* OR *\\Windows\\Temp\\*)) OR (event_id:"5007"
        AND OldValue.keyword:*\\Windows\ Defender\\Windows\ Defender\ Exploit\ Guard\\Controlled\
        Folder\ Access\\ProtectedFolders\\*))
index: wazuh-alerts*
name: win_defender_config_change_exploit_guard_tamper
priority: 2
realert:
  minutes: 0
type: any

is_enabled: true
timestamp_type: iso
timestamp_field: '@timestamp'
