author: Florian Roth (Nextron Systems)
date: 2017/05/09
description: This rule detects a suspicious crash of the Microsoft Malware Protection
  Engine
detection:
  condition: selection
  selection:
    Data|contains|all:
    - MsMpEng.exe
    - mpengine.dll
    EventID: 1001
    Provider_Name: Windows Error Reporting
falsepositives:
- MsMpEng might crash if the "C:\" partition is full
id: 6c82cf5c-090d-4d57-9188-533577631108
level: high
logsource:
  product: windows
  service: application
modified: 2023/04/14
references:
- https://bugs.chromium.org/p/project-zero/issues/detail?id=1252&desc=5
- https://technet.microsoft.com/en-us/library/security/4022344
status: test
tags:
- attack.defense_evasion
- attack.t1211
- attack.t1562.001
title: Microsoft Malware Protection Engine Crash - WER
