author: frack113
date: 2022/10/02
description: Detects registry modifications that disable Privacy Settings Experience
detection:
  condition: selection
  selection:
    Details: DWORD (0x00000000)
    TargetObject|endswith: \SOFTWARE\Policies\Microsoft\Windows\OOBE\DisablePrivacyExperience
falsepositives:
- Legitimate admin script
id: 0372e1f9-0fd2-40f7-be1b-a7b2b848fa7b
level: medium
logsource:
  category: registry_set
  product: windows
modified: 2023/08/17
references:
- https://github.com/redcanaryco/atomic-red-team/blob/9e5b12c4912c07562aec7500447b11fa3e17e254/atomics/T1562.001/T1562.001.md
status: experimental
tags:
- attack.defense_evasion
- attack.t1562.001
title: Disable Privacy Settings Experience in Registry
