author: frack113
date: 2021/11/26
description: 'Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of
  Windows Defender used to manage settings in Windows Defender.

  Users can configure different pilot collections for each of the co-management workloads.

  It can be abused by attackers in order to upload or download files.

  '
detection:
  condition: all of selection_*
  selection_img:
  - CommandLine|contains: ConfigSecurityPolicy.exe
  - Image|endswith: \ConfigSecurityPolicy.exe
  - OriginalFileName: ConfigSecurityPolicy.exe
  selection_url:
    CommandLine|contains:
    - ftp://
    - http://
    - https://
falsepositives:
- Unknown
id: 1f0f6176-6482-4027-b151-00071af39d7e
level: medium
logsource:
  category: process_creation
  product: windows
modified: 2022/05/16
references:
- https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
status: test
tags:
- attack.exfiltration
- attack.t1567
title: Arbitrary File Download Via ConfigSecurityPolicy.EXE
