author: frack113
date: 2022/01/28
description: Uninstall an application with wmic
detection:
  condition: all of selection_*
  selection_cli:
    CommandLine|contains:
    - call
    - uninstall
  selection_img:
  - Image|endswith: \WMIC.exe
  - OriginalFileName: wmic.exe
falsepositives:
- Unknown
id: b53317a0-8acf-4fd1-8de8-a5401e776b96
level: medium
logsource:
  category: process_creation
  product: windows
modified: 2023/02/14
references:
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
related:
- id: 847d5ff3-8a31-4737-a970-aeae8fe21765
  type: derived
status: test
tags:
- attack.execution
- attack.t1047
title: Application Removed Via Wmic.EXE
