alert:
- debug
description: "Detects the addition of a SSP to the registry. Upon a reboot or API
  call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.\n"
filter:
- query:
    query_string:
      query: (registry_key_path.keyword:(*\\Control\\Lsa\\Security\ Packages OR *\\Control\\Lsa\\OSConfig\\Security\
        Packages) AND (NOT ((process_path:("C\:\\Windows\\system32\\msiexec.exe" OR
        "C\:\\Windows\\syswow64\\MsiExec.exe")))))
index: wazuh-alerts*
name: registry_event_ssp_added_lsa_config
priority: 2
realert:
  minutes: 0
type: any

is_enabled: true
timestamp_type: iso
timestamp_field: '@timestamp'
