alert:
- debug
description: Detects installation of new shim databases that try to patch sections
  of known processes for potential process injection or persistence.
filter:
- query:
    query_string:
      query: (registry_key_path.keyword:*\\SOFTWARE\\Microsoft\\Windows\ NT\\CurrentVersion\\AppCompatFlags\\Custom\\*
        AND registry_key_path.keyword:(*\\csrss.exe OR *\\dllhost.exe OR *\\explorer.exe
        OR *\\RuntimeBroker.exe OR *\\services.exe OR *\\sihost.exe OR *\\svchost.exe
        OR *\\taskhostw.exe OR *\\winlogon.exe OR *\\WmiPrvSe.exe))
index: wazuh-alerts*
name: registry_set_persistence_shim_database_susp_application
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
