alert:
- debug
description: Detects when changes are made to PIM roles
filter:
- query:
    query_string:
      query: properties.message:"Update\ role\ setting\ in\ PIM"
index: wazuh-alerts*
name: azure_pim_change_settings
priority: 2
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
