author: iwillkeepwatch
date: 2019/01/18
description: 'Detects the addition of a SSP to the registry. Upon a reboot or API
  call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.

  '
detection:
  condition: selection and not 1 of filter_main_*
  filter_main_msiexec:
    Image:
    - C:\Windows\system32\msiexec.exe
    - C:\Windows\syswow64\MsiExec.exe
  selection:
    TargetObject|endswith:
    - \Control\Lsa\Security Packages
    - \Control\Lsa\OSConfig\Security Packages
falsepositives:
- Unknown
id: eeb30123-9fbd-4ee8-aaa0-2e545bbed6dc
level: high
logsource:
  category: registry_event
  product: windows
modified: 2022/08/09
references:
- https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
- https://github.com/EmpireProject/Empire/blob/08cbd274bef78243d7a8ed6443b8364acd1fc48b/data/module_source/persistence/Install-SSP.ps1#L157
status: test
tags:
- attack.persistence
- attack.t1547.005
title: Security Support Provider (SSP) Added to LSA Configuration
