alert:
- debug
description: Detects enumeration of Kubernetes secrets.
filter:
- query:
    query_string:
      query: (verb:"list" AND objectRef.resource:"secrets")
index: wazuh-alerts*
name: kubernetes_audit_secrets_enumeration
priority: 4
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
