alert:
- debug
description: |
  Detects deployments of pods within the kube-system namespace, which could be intended to imitate system pods.
  System pods, created by controllers such as Deployments or DaemonSets have random suffixes in their names.
  Attackers can use this fact and name their backdoor pods as if they were created by these controllers to avoid detection.
  Deployment of such a backdoor container e.g. named kube-proxy-bv61v, could be attempted in the kube-system namespace alongside the other administrative containers.
filter:
- query:
    query_string:
      query: (verb:"create" AND objectRef.resource:"pods" AND objectRef.namespace:"kube\-system")
index: wazuh-alerts*
name: kubernetes_audit_pod_in_system_namespace
priority: 3
realert:
  minutes: 0
type: any

is_enabled: false
timestamp_type: '@timestamp'
