alert:
- debug
description: "Detects creation of new Kubernetes service account, which could indicate
  an attacker's attempt to persist within a cluster.\n"
filter:
- query:
    query_string:
      query: (verb:"create" AND objectRef.resource:"serviceaccounts")
index: wazuh-alerts*
name: kubernetes_audit_serviceaccount_creation
priority: 4
realert:
  minutes: 0
type: any

is_enabled: false
